image:
  file: .gitpod.Dockerfile

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true

tasks:
  - name: Create local cluster
    init: k3d cluster create
    openMode: split-right
  - name: Configure Pulumi credentials
    init: pulumi config set gcp:credentials $GCP_CREDENTIALS